// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeriesSite.Infrastructure;

namespace SeriesSite.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200521142053_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SeriesSite.Infrastructure.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SerialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SerialId")
                        .IsUnique()
                        .HasFilter("[SerialId] IS NOT NULL");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("SeriesSite.Infrastructure.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SerialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SerialId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("SeriesSite.Infrastructure.Models.Serial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Serials");
                });

            modelBuilder.Entity("SeriesSite.Infrastructure.Models.Country", b =>
                {
                    b.HasOne("SeriesSite.Infrastructure.Models.Serial", "Serial")
                        .WithOne("Country")
                        .HasForeignKey("SeriesSite.Infrastructure.Models.Country", "SerialId");
                });

            modelBuilder.Entity("SeriesSite.Infrastructure.Models.Genre", b =>
                {
                    b.HasOne("SeriesSite.Infrastructure.Models.Serial", "Serial")
                        .WithMany("Genres")
                        .HasForeignKey("SerialId");
                });
#pragma warning restore 612, 618
        }
    }
}
